anchor_version = "0.25.0"

[workspace]
members = [
    ".",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
serum_dex = "Dex9ZPjNQmvS3HHBrNRcnX7aUvSosLH9AZWPwpXu3TJz"
